openapi: 3.0.0
info:
  title: Backend API
  version: 1.0.0
servers:
  - url: http://localhost:3000/api/v1
paths:
  /health:
    get:
      summary: app health endpoint
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
  /public:
    get:
      summary: get public data
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
  /objects:
    post:
      summary: persist object
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
              required:
                - name
      responses:
        "201":
          description: Created
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
